//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalizationResourceManager.Maui.Sample.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalizationResourceManager.Maui.Sample.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cute dot net bot waving hi to you!.
        /// </summary>
        internal static string BotDescription {
            get {
                return ResourceManager.GetString("BotDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicked {0} times.
        /// </summary>
        internal static string ClickedManyTimes {
            get {
                return ResourceManager.GetString("ClickedManyTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicked {0} time.
        /// </summary>
        internal static string ClickedOneTime {
            get {
                return ResourceManager.GetString("ClickedOneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click me.
        /// </summary>
        internal static string ClickMe {
            get {
                return ResourceManager.GetString("ClickMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts the number of times you click.
        /// </summary>
        internal static string CounterBtnHint {
            get {
                return ResourceManager.GetString("CounterBtnHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle language.
        /// </summary>
        internal static string ToggleLanguage {
            get {
                return ResourceManager.GetString("ToggleLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to dot net Multi platform App U I.
        /// </summary>
        internal static string WelcomeToMAUI {
            get {
                return ResourceManager.GetString("WelcomeToMAUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        internal static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
    }
}
